### ISSUE TITLE
How to use a 2nd SPI?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [AntoineHZ/oled-js-pi#1]
If I have 2 (or even 5) SPI devices (Rpi is capabable of this), how does this library address them? I don't see in the example, any choice of chip-selects.

**Comment by ijoijo** [comment]
You should be able to change the SPI device in var opts, default is :
   device: "/dev/spidev0.0";

Let me know whether this works, I will update the documentation accordingly.

**Comment by GeoffreyPlitt** [comment]
Thank you!
